### ISSUE TITLE
Update Octopress.org (appears unmaintained to the casual observer)

### ISSUE THREAD

**Issue by jtwalters** [octopress/docs#20]
The last post was from 2011. Shouldn't the site be updated to mention new work that's been completed, e.g., Octopress 3.0?

**Comment by ke352802081770314** [comment]
Almost two years have elapsed since your statement. No software is ever "completed". 
I recently set up a blog with octopress 3 and I find it disappointing that this actively developed project is hidden, as the obvious URL octopress.org still refers to version 2 only, and only third-party how-tos are available for a gentle introduction.
